version: "3.8"

services:
  app:
    container_name: bespoke-db
    restart: always

    environment:
      - DB_HOST=mongo
      - DB_NAME=bespoke-db
    links:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mongo:
    image: "mongo:4"

    ports:
      - "27017:27017"
