import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/header";
import { Inter as FontSans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import footer from "@/components/Footer/footer";
import Footer from "@/components/Footer/footer";
import { Avatar } from "@/components/ui/avatar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  icons: "/assets/companylogo.png",
  title: "Bespoke Electric",
  description: "Generated by Scotty Intondi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col">
            <Header />
            <div className="min-h-full">{children}</div>
            <div className="top-10 sticky">
              <Footer />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
